[package]
name = "trust"
version = "0.1.0"
authors = ["Ritvik Annam <rannam@cs.utexas.edu>"]

[dependencies]
time = "0.1.12"
bufstream = "0.1.3"
tk-bufstream = "0.3.0"
maplit = "1.0.1"
lazy_static = "1.0.0"
regex = "1.0.0"
